version: "3.7"
services:
  database_openings:
    image: postgres
    container_name: database_openings
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=openings
      - POSTGRES_PASSWORD=@openings
      - POSTGRES_DB=openingsdb
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: api_openings
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  pgdata:
    driver: local
